version: '3'

services:
  reverse-proxy:
    image: traefik:2.7
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  crm-server:
    build:
      context: ./server
    ports:
      # порт для отладки
      - "5005:5005"
      # порт для доступа к бэкенду снаружи
      - "9010:9010"
    labels:
      - "traefik.http.routers.crm-server.rule=PathPrefix(`/api`)"
      # не знаю зачем была зделана обрезка префиксов, убрал
      # Create a middleware named `crm-server-stripprefix`
      # - "traefik.http.middlewares.crm-server-stripprefix.stripprefix.prefixes=/api"
      # Apply the middleware named `crm-server-stripprefix` to the router named `crm-server`
      # - "traefik.http.routers.crm-server.middlewares=crm-server-stripprefix@docker"
      # Tell Traefik to use the port 9010 to connect to `crm-server`, если порт один то строчка не нужна 
      - "traefik.http.services.crm-server.loadbalancer.server.port=9010"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /opt/api-0.0.1-SNAPSHOT.jar

  crm-client:
    image: marcnuri/isotope:client-latest
    # если нужен порт для доступа к фронтенду снаружи то разкоментить 
    # ports:
    #   - "8081:80"
    labels:
      - "traefik.http.routers.crm-client.rule=PathPrefix(`/`)"
