## http routing section
http:
  # Add the router
  routers:
    # Define a connection between requests and services
    to_server:
      rule: PathPrefix(`/api`)
      # If the rule matches, forward to the service (declared below)
      service: spring_local
      entryPoints:
        - web

  # Add the service
  services:
    # Define how to reach an existing service on our infrastructure
    spring_local:
      loadBalancer:
        servers:
          # On Linux, for versions of Docker older than 20.10.0, for host.docker.internal to be defined,
          # it should be provided as an extra_host to the Traefik container, using the --add-host flag.
          #For example, to set it to the IP address of the bridge interface (docker0 by default):
          #  --add-host=host.docker.internal:172.17.0.1
          - url: http://host.docker.internal:9010/